# Generated by Django 6.0.3 on 2026-03-13 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('table_preference', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('private', 'Private Room'), ('any', 'No Preference')], default='any', max_length=20)),
                ('occasion', models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('business', 'Business Dinner'), ('date', 'Date Night'), ('family', 'Family Gathering'), ('other', 'Other'), ('', 'None')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
